### ISSUE TITLE
Scraper: casos importados

### ISSUE THREAD

**Issue by leobezerra** [leobezerra/covid19#7]
O boletim epidemiológico relata os casos importados em uma tabela separada.

Estes casos não estão sendo coletados pelo scraper no momento.

**O que fazer?**
- Expandir o scraper para coletar os casos da tabela de casos importados
- Contabilizar esses casos como sendo referentes a Natal

**Comment by leobezerra** [comment]
* O commit 03fb9dd expandiu o scraper pra coletar os casos da tabela de casos importados.
* A contabilização ainda está pendente. Por não haver consenso sobre como contabilizar os casos, vamos deixar os casos identificados como "Importados".

**Comment by leobezerra** [comment]
O parser agora está correto e os CSVs para as datas que ele consegue processar, também.

É necessário ainda que alguém atualize os CSVs anteriores ao dia 24-03-2020.

**O que fazer?**
- Coletar os boletins anteriores ao dia 24-03-2020
- Adicionar uma linha aos CSVs correspondentes informando o número de casos importados confirmados e suspeitos (Tabela 2)

* Conferir com os outros CSVs pra manter o padrão!

**Comment by vitor-saldanha** [comment]
Terminei de atualizar todos com a nova linha de importados. Também adicionei na tabela do excel e já upei ela.
